import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | Searoutestrade',
    default: 'Searoutestrade',
  },
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/static/images/icon.png',
        href: '/static/images/icon.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/static/images/icon.png',
        href: '/static/images/icon.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <GoogleAnalytics gaId="G-TDKBMNXWBH" />
    </html>
  );
}
